### ISSUE TITLE
Readme??

### ISSUE THREAD

**Issue by techker** [Gemorroj/M3uParser#13]
Can somebody explain how to use this?
always get PHP Fatal error:  Class 'M3uParser\M3uParser' not found in

do I put the all the file is a folder M3uParser?or root

**Comment by Gemorroj** [comment]
Have you used [composer](https://getcomposer.org/doc/00-intro.md)?
Perhaps you need to add `require 'vendor/autoload.php';`

**Comment by bgjett1965** [comment]
I’m screwed with this too.  Need to be more proficient with this but until that time, a step by step would be appreciated.  Wish I could I help

**Comment by Gemorroj** [comment]
Use `composer`. It is easy and convenient.
