### ISSUE TITLE
Add all iptv tags

### ISSUE THREAD

**Issue by Gemorroj** [Gemorroj/M3uParser#19]
https://en.wikipedia.org/wiki/M3U#Extended_M3U

**Comment by Gemorroj** [comment]
- [x] EXTINF key-value
- [x] PLAYLIST
- [x] EXTGRP

**Comment by jusurb** [comment]
while not documented in the wiki, but would be great to also add `#EXTVLCOPT` tag:
```
#EXTVLCOPT:http-user-agent=WINK/1.28.2 (AndroidTV/9) HlsWinkPlayer
```
