### ISSUE TITLE
url is parsed twice

### ISSUE THREAD

**Issue by veso266** [Gemorroj/M3uParser#3]
Hi the url in a m3u file is shown twice if I do: echo $entry->getPath() I will get 

Alternative\everclear_SMFTA.mp3
Alternative\everclear_SMFTA.mp3

out of this file: 
# EXTM3U
# EXTINF:233,Everclear - So Much For The Afterglow

Alternative\everclear_SMFTA.mp3

**Comment by Gemorroj** [comment]
thx. fixed.
