### ISSUE TITLE
Call to a member function getIconUrl() on null 

### ISSUE THREAD

**Issue by naja7host** [Gemorroj/M3uParser#7]
whe  the icon is empty , the fallowing error appear in error reporting is true .

**Comment by Gemorroj** [comment]
plz, add example playlist

**Comment by naja7host** [comment]
#EXTINF:-1 tvg-ID="" tvg-name="MEDI 1 SAT" tvg-logo="" group-title="ARABIC",MEDI 1 SAT

the same for set icon url 
$entry->getExtTv()->setIconUrl("http://placehold.it/400x250/000/fff");

**Comment by Gemorroj** [comment]
There is no tag EXTTV.
See:
[M3uParser/Entry.php#L52](../blob/master/src/M3uParser/Entry.php#L52)
If there is no tag, it will be `NULL`.

possible fix:
```php
use M3uParser\Tag\ExtTv;

$extTv = new ExtTv();
$extTv->setIconUrl("http://placehold.it/400x250/000/fff");
$entry->setExtTv($extTv);

**Comment by naja7host** [comment]
i think this related to ExtInf ? 
may be we need to add support for this also like Eexttv .

**Comment by Gemorroj** [comment]
I don't understand (
Can you tell us in more detail.

**Comment by naja7host** [comment]
From you tag file extinf the example exist 

`#EXTINF:-1 tvg-name=Первый_HD tvg-logo="Первый канал" deinterlace=4 group-title="Эфирные каналы",Первый канал HD`

the actual class didn't recognise the logo of the title , only it return the name with getTitle() function . so to get the logo no exist any cal for it .

we need something like this 
$entry->getExtInf()->getIconUrl()

**Comment by Gemorroj** [comment]
Ahh, Yes, now not supported `tvg` attributes.

**Comment by naja7host** [comment]
any way to see it implemented ?

**Comment by Gemorroj** [comment]
It takes time and desire =)

**Comment by Gemorroj** [comment]
Created a task to implement a attributes #8 .

**Comment by Gemorroj** [comment]
implemented
