### ISSUE TITLE
How can i download and use it without composer?

### ISSUE THREAD

**Issue by onigetoc** [Gemorroj/M3uParser#9]
I have a shared server
How can i download and use it without composer?

**Comment by Gemorroj** [comment]
I have not tested this possibility.
But composer can be installed locally, simply by downloading the phar `https://getcomposer.org/download/1.3.2/composer.phar`

**Comment by onigetoc** [comment]
Hi, what should i do after that?
i find no explanation or help online about this file, only about Composer-Setup.exe 
and you should install php on our computer i think

**Comment by onigetoc** [comment]
What i see it's i only need to add autoload in composer.
how do i set up a demo php file?
with witch require file in php in the top?

Do it will parse this file?
http://pastebin.com/raw/Z7ntMnF8

**Comment by Gemorroj** [comment]
I made a video with the installation of the m3u-parser using composer.
[http://wapinet.ru/static/file//2017/02/27/58b47e5d0ac95.mp4](http://wapinet.ru/static/file//2017/02/27/58b47e5d0ac95.mp4) ([Online player](http://wapinet.ru/file/39067))

**Comment by onigetoc** [comment]
I tryed php and composer on my computer.
i do not understand the use of hundred of files for a script that should work in one php file.

**Comment by onigetoc** [comment]
lol, online player do not work and i'm not russian



2017-02-27 14:37 GMT-05:00 Gemorroj <notifications@github.com>:

**Comment by Gemorroj** [comment]
The sound was accidentally recorded. It is not at all about the composer there)
